### ISSUE TITLE
No records in Equation-object

### ISSUE THREAD

**Issue by sebwehrle** [GAMS-dev/gamspy#11]
When querying an Equation symbol from a GDX file using gamspy version 1.0 in Python 3.10.13, the returned object shows zero records, and the records themselves are empty. However, when opening the same GDX file in GAMS Studio, the records are present. Additionally, when using gams.transfer, the records are correctly returned. Records for other objects such as sets, parameters, and variables are correctly returned when queried using gamspy.

```python
from gamspy import Container

m = Container("/path/to/gdx/filename.gdx")
eq = m.getSymbols("equation_name")
df = eq[0].records
print(df)  # df is None
print(eq[0].number_records)  # Returns 0
```

OS: Ubuntu 22.04

**Comment by mabdullahsoyturk** [comment]
Fixed with 1.0.1.
