### ISSUE TITLE
Rust bindings to read and write gdx

### ISSUE THREAD

**Issue by areleu** [GAMS-dev/gamspy#2]
Sorry I write the issue here, it was intended for https://github.com/GAMS-dev/gdx/ but there is no issue board in that repo. I was wondering if you are considering the implementation of a Rust API to work with GDX files. Maybe not a full GAMS interface but at least some handling tools would be great.

**Comment by 0x17** [comment]
Thanks for the comment. I've added an issue board to the GDX repo and created an issue for your request, see https://github.com/GAMS-dev/gdx/issues/1.

There are no plans for a GAMS/GDX Rust API yet, but it might be something we should look into as Rust is gaining traction. Right now I would assume the easiest way to read/write GDX files from Rust is either the [C++ OOP API](https://github.com/GAMS-dev/gams-cpp) or the low-level C interface (e.g. via `gdxcc.h`).

**Comment by areleu** [comment]
Great, then I will close this issue, and continue the discussion in the correct board.
