### ISSUE TITLE
Update of IPOPT package

### ISSUE THREAD

**Issue by grecht** [GAMS-dev/gamspy#9]
IPOPT hasn't been updated, so I'm currently stuck on GAMSPy 0.13.2. I depend on IPOPT for my research and since quite a few improvements have been made to GAMSPy it'd be nice to have the update!

**Comment by mabdullahsoyturk** [comment]
@grecht IPOPT is one of the default solvers now and comes with gamspy_base package. So, there is no need for extra package installation anymore. You can just install the latest gamspy and set your solver as "IPOPT" in your solve statement.

**Comment by grecht** [comment]
Ah, great! Thank you. Sorry for not spotting this.
